# From https://dev.to/brunorobert/github-and-gitlab-sync-44mn
name: SCSGitLabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: SCSGitLabSync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        # Such as https://github.com/wangchucheng/git-repo-sync.git
        target-url: ${{ secrets.SCS_GITLAB_REPO }}
        # Such as wangchucheng
        target-username: ${{ secrets.SCS_GITLAB_USERNAME }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.SCS_GITLAB_REPO_TOKEN }}
